### ISSUE TITLE
NineOldAndroids

### ISSUE THREAD

**Issue by GuilhE** [daimajia/AnimationEasingFunctions#5]
Hello,
Since NineOldAndroids is deprecated when will you remove this dependency from this lib?
Thanks.

**Comment by daimajia** [comment]
@GuilhE  the next version will remove `NineOldAndroids`. :-D

**Comment by lsjwzh** [comment]
可以拆成两个库么？一个支持NineOldAndroids，一个移除NineOldAndroids

**Comment by jaredrummler** [comment]
This class contains all the animations from the library in one class and doesn't use NineOldAndroids:

https://gist.github.com/jaredrummler/206c910451a55b610462

**Comment by daimajia** [comment]
Since version 2.0, NineOldAndroids has been removed.
