### ISSUE TITLE
Release .aar contains ic_launcher.png in drawable-hdpi-v4

### ISSUE THREAD

**Issue by jjhorgan** [daimajia/AnimationEasingFunctions#9]
All resources should be namespaced.
And maybe default generated resources should not be included in released builds
This will cause aapt duplicate file errors if imported into a project that has a default generated ic_launcher file in a drawable-hdpi directory.

**Comment by j796160836** [comment]
+1 for this issue

**Comment by daimajia** [comment]
The icon file has been removed already, so close this issue. Thanks for your feedback.
